### ISSUE TITLE
Cross Compatibility

### ISSUE THREAD

**Issue by chaoscalm** [duraki/charles-keygen#1]
Hello, I tried it on Windows but seems return different values than another one, I suspect a missing XORCheck.

**Comment by duraki** [comment]
Post screenshot of the terminal or give me your terminal output (stdout//stderr).

**Comment by duraki** [comment]
You can also try to patch it via [charles-hacking](https://github.com/100apps/charles-hacking/issues/37#issuecomment-620773054). The website works fine.

**Comment by chaoscalm** [comment]
My test is done with: https://github.com/ojdkbuild/ojdkbuild on Windows Platform,

Example: the output here is coherent with your output: 

![duraki](https://user-images.githubusercontent.com/7214961/80529967-9a996580-8998-11ea-8028-60fd6b1e391a.png)

Except result is different:
 
![mesmerize](https://user-images.githubusercontent.com/7214961/80530157-e815d280-8998-11ea-816a-e1dd3ef0f0d7.png)

For that reason I believe there is something.

I can provide further information, if you illustrate me. Thank you.

**Comment by duraki** [comment]
I don't get it. The terminal output is the same as in the README//repo and it works just fine?
