### ISSUE TITLE
Not working with 4.5.6

### ISSUE THREAD

**Issue by MestreKarin** [duraki/charles-keygen#2]
![image](https://user-images.githubusercontent.com/19618186/81624952-e7842f80-93cd-11ea-99f6-3e1557b2dad7.png)

I tested that web generator too, didn't worked (app freezes at splash screen).

**Comment by duraki** [comment]
I did not test this on WinNT. Give me username + serial & Charles bin `md5sum`.

**Comment by MestreKarin** [comment]
Charles.exe: b0660f001b8ee88720769925c64d0b43
Charles.jar: 3cd04838a11eea446fad301754a0d705

The keys I tested:
Mestre Karin - E2EDCAEE632DEE2596
0XDURAKI - DBABE8D539FBD26406

**Comment by duraki** [comment]
Possibly incorrect version? Spits:

`abfcad313ee9172e74329552f72e44d0  charles.jar` for me

**Comment by MestreKarin** [comment]
Maybe the jar files are different for each platform (this would explain why the jar file from that web generator freezes at splash screen)?

Checked again with microsoft tool.

`3cd04838a11eea446fad301754a0d705 c:\program files\charles\lib\charles.jar`

![image](https://user-images.githubusercontent.com/19618186/81726759-45605800-945e-11ea-97f9-c56f1dc8b501.png)

**Comment by duraki** [comment]
Ah, crap. You are right. It might be platform dependent. I suspect some offsets are different on WinNT platform. 
  
Are you running x64 or x86? I don't have WinNT VM rn so I can't test it further. Will check out once I get time.

**Comment by MestreKarin** [comment]
I'm running x64.

**Comment by liudongmiao** [comment]
@MestreKarin 

> Mestre Karin - E2EDCAEE632DEE2596
> 0XDURAKI - DBABE8D539FBD26406

Could you check this: (not the keygen by @duraki )
Mestre Karin - ~removed~
0XDURAKI - ~removed~

**Comment by liudongmiao** [comment]
@duraki even with macOS, the name / value pair doesn't work.
You can run `Bvcn.FwRs` for the name to get the result.

**Comment by MestreKarin** [comment]
Worked like a charm. Thank you sir.

![image](https://user-images.githubusercontent.com/19618186/82127532-b1a6c880-978a-11ea-90c4-d4667474e69c.png)

**Comment by liudongmiao** [comment]
Just open source the keygen: https://gitee.com/thom/charles-keygen (in Chinese)

**Comment by duraki** [comment]
Much better solution. Closing.
