### ISSUE TITLE
not working with 4.6.1

### ISSUE THREAD

**Issue by iM0hamed** [duraki/charles-keygen#3]
not working with 4.6.1

**Comment by helloyanis** [comment]
I'm late but try these
Username :
`Cracked`
Key :
`05aeeaadc069f0ab2c`

**Comment by duraki** [comment]
As of #4 this should be fixed really soon.

**Comment by bastetcheat** [comment]
it doesn't work version => 4.6.2
`java CharlesKeygen "Cracked"`


* GENERATED LICENSE:
  [Cracked:D83C6213CD58288CB8]
  
  this username and password is working 
  Username :
Cracked
Key :
05aeeaadc069f0ab2c

update the script please

**Comment by Chromium420** [comment]
> I'm late but try these Username : `Cracked` Key : `05aeeaadc069f0ab2c`

Thanks worked <#3

**Comment by duraki** [comment]
Fixed now with #4 :)
